production:
  adapter: postgresql
  database: unicorn_development
  host: localhost

development:
  adapter: postgresql
  database: unicorn_development
  host: localhost

test:
  adapter: postgresql
  database: unicorn_test
  host: localhost
